version: "3"

networks:
  ingress_default:
    external: true

services:
#  training-oaxaca-com:
#    image: registry.wsantos.net/oaxaca-com/training-oaxaca-com:latest
#    restart: always
#    networks:
#      - "ingress_default"
#    environment:
#      - "SERVER_HOST=0.0.0.0"
#      - "SERVER_PORT=8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.frontend.rule=Host:training-oaxaca-com.wsantos.net"
#      - "traefik.docker.network=ingress_default"

#  waiting-oaxaca-com:
#    image: registry.wsantos.net/oaxaca-com/waiting-oaxaca-com:latest
#    restart: always
#    networks:
#      - "ingress_default"
#    environment:
#      - "SERVER_HOST=0.0.0.0"
#      - "SERVER_PORT=8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.frontend.rule=Host:waiting-oaxaca-com.wsantos.net"
#      - "traefik.docker.network=ingress_default"

  menu-oaxaca-com:
    image: registry.wsantos.net/oaxaca-com/menu-oaxaca-com:latest
    restart: always
    networks:
      - "ingress_default"
    environment:
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=8080"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:menu-oaxaca-com.wsantos.net"
      - "traefik.docker.network=ingress_default"
