version: "3"

networks:
  postgres:
  ingress_default:
    external: true

services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - "postgres"
    environment:
      - "POSTGRES_PASSWORD=%hJl7£21bSpp./ws"
    volumes:
      - "/home/oaxaca-com/mount/api-oaxaca-com/postgres:/var/lib/postgresql/data"
    labels:
      - "traefik.enable=false"

  api-oaxaca-com:
    image: registry.wsantos.net/oaxaca-com/api-oaxaca-com:latest
    restart: always
    networks:
      - "postgres"
      - "ingress_default"
    environment:
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=8080"
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_USER=oaxaca"
      - "DB_PASS=oaxaca"
      - "DB_NAME=oaxaca"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api-oaxaca-com.wsantos.net"
      - "traefik.docker.network=ingress_default"
